/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XaiRiskOverviewRouteImport } from './routes/xai-risk-overview'
import { Route as UserSigninRouteImport } from './routes/user-signin'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LmsRouteImport } from './routes/lms'
import { Route as LearningStyleOverviewRouteImport } from './routes/learning-style-overview'
import { Route as LearningStyleRouteImport } from './routes/learning-style'
import { Route as EngagementOverviewRouteImport } from './routes/engagement-overview'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminSigninRouteImport } from './routes/admin-signin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const XaiRiskOverviewRoute = XaiRiskOverviewRouteImport.update({
  id: '/xai-risk-overview',
  path: '/xai-risk-overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/xai-risk-overview.lazy').then((d) => d.Route),
)
const UserSigninRoute = UserSigninRouteImport.update({
  id: '/user-signin',
  path: '/user-signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user-signin.lazy').then((d) => d.Route))
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const LmsRoute = LmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lms.lazy').then((d) => d.Route))
const LearningStyleOverviewRoute = LearningStyleOverviewRouteImport.update({
  id: '/learning-style-overview',
  path: '/learning-style-overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/learning-style-overview.lazy').then((d) => d.Route),
)
const LearningStyleRoute = LearningStyleRouteImport.update({
  id: '/learning-style',
  path: '/learning-style',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/learning-style.lazy').then((d) => d.Route),
)
const EngagementOverviewRoute = EngagementOverviewRouteImport.update({
  id: '/engagement-overview',
  path: '/engagement-overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/engagement-overview.lazy').then((d) => d.Route),
)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/engagement.lazy').then((d) => d.Route))
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs.lazy').then((d) => d.Route))
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const AdminSigninRoute = AdminSigninRouteImport.update({
  id: '/admin-signin',
  path: '/admin-signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin-signin.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-signin': typeof AdminSigninRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/engagement': typeof EngagementRoute
  '/engagement-overview': typeof EngagementOverviewRoute
  '/learning-style': typeof LearningStyleRoute
  '/learning-style-overview': typeof LearningStyleOverviewRoute
  '/lms': typeof LmsRoute
  '/pricing': typeof PricingRoute
  '/user-signin': typeof UserSigninRoute
  '/xai-risk-overview': typeof XaiRiskOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-signin': typeof AdminSigninRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/engagement': typeof EngagementRoute
  '/engagement-overview': typeof EngagementOverviewRoute
  '/learning-style': typeof LearningStyleRoute
  '/learning-style-overview': typeof LearningStyleOverviewRoute
  '/lms': typeof LmsRoute
  '/pricing': typeof PricingRoute
  '/user-signin': typeof UserSigninRoute
  '/xai-risk-overview': typeof XaiRiskOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-signin': typeof AdminSigninRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/engagement': typeof EngagementRoute
  '/engagement-overview': typeof EngagementOverviewRoute
  '/learning-style': typeof LearningStyleRoute
  '/learning-style-overview': typeof LearningStyleOverviewRoute
  '/lms': typeof LmsRoute
  '/pricing': typeof PricingRoute
  '/user-signin': typeof UserSigninRoute
  '/xai-risk-overview': typeof XaiRiskOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-signin'
    | '/analytics'
    | '/docs'
    | '/engagement'
    | '/engagement-overview'
    | '/learning-style'
    | '/learning-style-overview'
    | '/lms'
    | '/pricing'
    | '/user-signin'
    | '/xai-risk-overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-signin'
    | '/analytics'
    | '/docs'
    | '/engagement'
    | '/engagement-overview'
    | '/learning-style'
    | '/learning-style-overview'
    | '/lms'
    | '/pricing'
    | '/user-signin'
    | '/xai-risk-overview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-signin'
    | '/analytics'
    | '/docs'
    | '/engagement'
    | '/engagement-overview'
    | '/learning-style'
    | '/learning-style-overview'
    | '/lms'
    | '/pricing'
    | '/user-signin'
    | '/xai-risk-overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminSigninRoute: typeof AdminSigninRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DocsRoute: typeof DocsRoute
  EngagementRoute: typeof EngagementRoute
  EngagementOverviewRoute: typeof EngagementOverviewRoute
  LearningStyleRoute: typeof LearningStyleRoute
  LearningStyleOverviewRoute: typeof LearningStyleOverviewRoute
  LmsRoute: typeof LmsRoute
  PricingRoute: typeof PricingRoute
  UserSigninRoute: typeof UserSigninRoute
  XaiRiskOverviewRoute: typeof XaiRiskOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xai-risk-overview': {
      id: '/xai-risk-overview'
      path: '/xai-risk-overview'
      fullPath: '/xai-risk-overview'
      preLoaderRoute: typeof XaiRiskOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-signin': {
      id: '/user-signin'
      path: '/user-signin'
      fullPath: '/user-signin'
      preLoaderRoute: typeof UserSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lms': {
      id: '/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof LmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-style-overview': {
      id: '/learning-style-overview'
      path: '/learning-style-overview'
      fullPath: '/learning-style-overview'
      preLoaderRoute: typeof LearningStyleOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-style': {
      id: '/learning-style'
      path: '/learning-style'
      fullPath: '/learning-style'
      preLoaderRoute: typeof LearningStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-overview': {
      id: '/engagement-overview'
      path: '/engagement-overview'
      fullPath: '/engagement-overview'
      preLoaderRoute: typeof EngagementOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-signin': {
      id: '/admin-signin'
      path: '/admin-signin'
      fullPath: '/admin-signin'
      preLoaderRoute: typeof AdminSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminSigninRoute: AdminSigninRoute,
  AnalyticsRoute: AnalyticsRoute,
  DocsRoute: DocsRoute,
  EngagementRoute: EngagementRoute,
  EngagementOverviewRoute: EngagementOverviewRoute,
  LearningStyleRoute: LearningStyleRoute,
  LearningStyleOverviewRoute: LearningStyleOverviewRoute,
  LmsRoute: LmsRoute,
  PricingRoute: PricingRoute,
  UserSigninRoute: UserSigninRoute,
  XaiRiskOverviewRoute: XaiRiskOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
