"""GitHub service for creating pull requests."""

import logging
from typing import Dict, Any

import requests
from git import Repo

from app.config import Config
from app.models import PullRequestResult

logger = logging.getLogger(__name__)


class GitHubService:
    """Service for interacting with GitHub API."""

    def __init__(self):
        """Initialize GitHub service."""
        self.token = Config.GITHUB_TOKEN
        self.api_url = Config.GITHUB_API_URL
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        }

    def push_branch(self, repo: Repo, branch_name: str) -> None:
        """
        Push branch to GitHub.

        Args:
            repo: GitPython Repo object
            branch_name: Branch name to push

        Raises:
            Exception: If push fails
        """
        logger.info(f"Pushing branch {branch_name} to GitHub")

        try:
            origin = repo.remote(name="origin")
            origin.push(branch_name)

            logger.info(f"Successfully pushed {branch_name}")

        except Exception as e:
            logger.error(f"Failed to push branch: {str(e)}")
            raise

    def create_pull_request(
        self,
        repo_name: str,
        branch_name: str,
        base_branch: str,
        root_cause: str,
        summary: str,
        error_log: str,
    ) -> PullRequestResult:
        """
        Create a pull request on GitHub.

        Args:
            repo_name: Repository name in format 'org/repo'
            branch_name: Source branch name
            base_branch: Target branch name (usually 'main')
            root_cause: Root cause of the failure
            summary: Summary of the fix
            error_log: Original error log

        Returns:
            PullRequestResult with PR details

        Raises:
            Exception: If PR creation fails
        """
        logger.info(f"Creating pull request for {repo_name}")

        # Build PR title and body
        pr_title = "AI Fix: Pipeline Failure"
        pr_body = self._build_pr_body(root_cause, summary, error_log)

        # API endpoint
        url = f"{self.api_url}/repos/{repo_name}/pulls"

        # Request payload
        payload = {
            "title": pr_title,
            "head": branch_name,
            "base": base_branch,
            "body": pr_body,
            "maintainer_can_modify": True,
        }

        try:
            # Make API request
            response = requests.post(
                url, headers=self.headers, json=payload, timeout=30
            )

            response.raise_for_status()

            # Parse response
            pr_data = response.json()
            pr_number = pr_data["number"]
            pr_url = pr_data["html_url"]

            logger.info(f"Successfully created PR #{pr_number}: {pr_url}")

            # Add labels to PR
            self._add_labels(repo_name, pr_number, ["automated", "ai-fix"])

            return PullRequestResult(
                pr_number=pr_number, pr_url=pr_url, branch_name=branch_name
            )

        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to create pull request: {str(e)}")
            if hasattr(e, "response") and e.response is not None:
                logger.error(f"Response: {e.response.text}")
            raise

    def _build_pr_body(self, root_cause: str, summary: str, error_log: str) -> str:
        """Build pull request body with markdown formatting."""
        # Truncate error log if too long
        max_error_length = 1000
        truncated_error = (
            error_log
            if len(error_log) <= max_error_length
            else f"{error_log[:max_error_length]}..."
        )

        pr_body = f"""## AI-Generated Fix

This pull request was automatically generated by the AI Failure Analyzer service.

### Root Cause
{root_cause}

### Changes Made
{summary}

### Original Error Log
```
{truncated_error}
```

### Important
- This is an automated fix generated by AI
- Please review the changes carefully before merging
- Run tests to verify the fix works as expected
- The fix follows minimal change principles

---
*Generated by AI Failure Analyzer Service*
"""
        return pr_body

    def _add_labels(self, repo_name: str, pr_number: int, labels: list[str]) -> None:
        """
        Add labels to pull request.

        Args:
            repo_name: Repository name
            pr_number: Pull request number
            labels: List of label names
        """
        url = f"{self.api_url}/repos/{repo_name}/issues/{pr_number}/labels"

        try:
            response = requests.post(
                url, headers=self.headers, json={"labels": labels}, timeout=30
            )

            if response.status_code == 200:
                logger.info(f"Added labels {labels} to PR #{pr_number}")
            else:
                logger.warning(f"Failed to add labels: {response.status_code}")

        except Exception as e:
            logger.warning(f"Could not add labels: {str(e)}")

    def get_repository_info(self, repo_name: str) -> Dict[str, Any]:
        """
        Get repository information from GitHub.

        Args:
            repo_name: Repository name in format 'org/repo'

        Returns:
            Repository information dictionary
        """
        url = f"{self.api_url}/repos/{repo_name}"

        try:
            response = requests.get(url, headers=self.headers, timeout=30)

            response.raise_for_status()
            return response.json()

        except Exception as e:
            logger.error(f"Failed to get repository info: {str(e)}")
            raise
